export const coins = [
  {acronym: 'AED', name: 'Dirham dos Emirados'},
  {acronym: 'AFN', name: 'Afghani do Afeganistão'},
  {acronym: 'ALL', name: 'Lek Albanês'},
  {acronym: 'AMD', name: 'Dram Armênio'},
  {acronym: 'ANG', name: 'Guilder das Antilhas'},
  {acronym: 'AOA', name: 'Kwanza Angolano'},
  {acronym: 'AZN', name: 'Manat Azeri'},
  {acronym: 'BAM', name: 'Marco Conversível'},
  {acronym: 'BBD', name: 'Dólar de Barbados'},
  {acronym: 'BDT', name: 'Taka de Bangladesh'},
  {acronym: 'BGN', name: 'Lev Búlgaro'},
  {acronym: 'BHD', name: 'Dinar do Bahrein'},
  {acronym: 'BIF', name: 'Franco Burundinense'},
  {acronym: 'BND', name: 'Dólar de Brunei'},
  {acronym: 'BOB', name: 'Boliviano'},
  {acronym: 'BRL', name: 'Real Brasileiro'},
  {acronym: 'BRLT', name: 'Real Brasileiro Turismo'},
  {acronym: 'BSD', name: 'Dólar das Bahamas'},
  {acronym: 'BTC', name: 'Bitcoin'},
  {acronym: 'BWP', name: 'Pula de Botswana'},
  {acronym: 'BYN', name: 'Rublo Bielorrusso'},
  {acronym: 'BZD', name: 'Dólar de Belize'},
  {acronym: 'CHFRTS', name: 'Franco Suíço'},
  {acronym: 'CNH', name: 'Yuan chinês offshore'},
  {acronym: 'CRC', name: 'Colón Costarriquenho'},
  {acronym: 'CUP', name: 'Peso Cubano'},
  {acronym: 'CVE', name: 'Escudo cabo-verdiano'},
  {acronym: 'CZK', name: 'Coroa Checa'},
  {acronym: 'DJF', name: 'Franco do Djubouti'},
  {acronym: 'DOGE', name: 'Dogecoin'},
  {acronym: 'DOP', name: 'Peso Dominicano'},
  {acronym: 'DZD', name: 'Dinar Argelino'},
  {acronym: 'EGP', name: 'Libra Egípcia'},
  {acronym: 'ETB', name: 'Birr Etíope'},
  {acronym: 'ETH', name: 'Ethereum'},
  {acronym: 'FJD', name: 'Dólar de Fiji'},
  {acronym: 'GBP', name: 'Libra Esterlina'},
  {acronym: 'GEL', name: 'Lari Georgiano'},
  {acronym: 'GHS', name: 'Cedi Ganês'},
  {acronym: 'GMD', name: 'Dalasi da Gâmbia'},
  {acronym: 'GNF', name: 'Franco de Guiné'},
  {acronym: 'GTQ', name: 'Quetzal Guatemalteco'},
  {acronym: 'HKD', name: 'Dólar de Hong Kong'},
  {acronym: 'HNL', name: 'Lempira Hondurenha'},
  {acronym: 'HRK', name: 'Kuna Croata'},
  {acronym: 'HTG', name: 'Gourde Haitiano'},
  {acronym: 'HUF', name: 'Florim Húngaro'},
  {acronym: 'IDR', name: 'Rupia Indonésia'},
  {acronym: 'ILS', name: 'Novo Shekel Israelense'},
  {acronym: 'INR', name: 'Rúpia Indiana'},
  {acronym: 'IQD', name: 'Dinar Iraquiano'},
  {acronym: 'IRR', name: 'Rial Iraniano'},
  {acronym: 'ISK', name: 'Coroa Islandesa'},
  {acronym: 'JMD', name: 'Dólar Jamaicano'},
  {acronym: 'JOD', name: 'Dinar Jordaniano'},
  {acronym: 'JPYRTS', name: 'Iene Japonês'},
  {acronym: 'KES', name: 'Shilling Queniano'},
  {acronym: 'KGS', name: 'Som Quirguistanês'},
  {acronym: 'KHR', name: 'Riel Cambojano'},
  {acronym: 'KMF', name: 'Franco Comorense'},
  {acronym: 'KRW', name: 'Won Sul-Coreano'},
  {acronym: 'KWD', name: 'Dinar Kuwaitiano'},
  {acronym: 'KYD', name: 'Dólar das Ilhas Cayman'},
  {acronym: 'KZT', name: 'Tengue Cazaquistanês'},
  {acronym: 'LAK', name: 'Kip Laosiano'},
  {acronym: 'LBP', name: 'Libra Libanesa'},
  {acronym: 'LKR', name: 'Rúpia de Sri Lanka'},
  {acronym: 'LSL', name: 'Loti do Lesoto'},
  {acronym: 'LTC', name: 'Litecoin'},
  {acronym: 'LYD', name: 'Dinar Líbio'},
  {acronym: 'MAD', name: 'Dirham Marroquino'},
  {acronym: 'MDL', name: 'Leu Moldavo'},
  {acronym: 'MGA', name: 'Ariary Madagascarense'},
  {acronym: 'MKD', name: 'Denar Macedônio'},
  {acronym: 'MMK', name: 'Kyat de Mianmar'},
  {acronym: 'MNT', name: 'Mongolian Tugrik'},
  {acronym: 'MOP', name: 'Pataca de Macau'},
  {acronym: 'MRO', name: 'Ouguiya Mauritana'},
  {acronym: 'MUR', name: 'Rúpia Mauriciana'},
  {acronym: 'MVR', name: 'Rufiyaa Maldiva'},
  {acronym: 'MWK', name: 'Kwacha Malauiana'},
  {acronym: 'MYR', name: 'Ringgit Malaio'},
  {acronym: 'MZN', name: 'Metical de Moçambique'},
  {acronym: 'NAD', name: 'Dólar Namíbio'},
  {acronym: 'NGN', name: 'Naira Nigeriana'},
  {acronym: 'NGNI', name: 'Naira Nigeriana'},
  {acronym: 'NGNPARALLEL', name: 'Naira Nigeriana'},
  {acronym: 'NIO', name: 'Córdoba Nicaraguense'},
  {acronym: 'NPR', name: 'Rúpia Nepalesa'},
  {acronym: 'OMR', name: 'Rial Omanense'},
  {acronym: 'PAB', name: 'Balboa Panamenho'},
  {acronym: 'PEN', name: 'Sol do Peru'},
  {acronym: 'PGK', name: 'Kina Papua-Nova Guiné'},
  {acronym: 'PHP', name: 'Peso Filipino'},
  {acronym: 'PKR', name: 'Rúpia Paquistanesa'},
  {acronym: 'PLN', name: 'Zlóti Polonês'},
  {acronym: 'PYG', name: 'Guarani Paraguaio'},
  {acronym: 'QAR', name: 'Rial Catarense'},
  {acronym: 'RON', name: 'Leu Romeno'},
  {acronym: 'RSD', name: 'Dinar Sérvio'},
  {acronym: 'RUB', name: 'Rublo Russo'},
  {acronym: 'RUBTOD', name: 'Rublo Russo'},
  {acronym: 'RUBTOM', name: 'Rublo Russo'},
  {acronym: 'RWF', name: 'Franco Ruandês'},
  {acronym: 'SAR', name: 'Riyal Saudita'},
  {acronym: 'SCR', name: 'Rúpias de Seicheles'},
  {acronym: 'SDG', name: 'Libra Sudanesa'},
  {acronym: 'SDR', name: 'DSE'},
  {acronym: 'SGD', name: 'Dólar de Cingapura'},
  {acronym: 'SOS', name: 'Shilling Somaliano'},
  {acronym: 'STD', name: 'Dobra São Tomé/Príncipe'},
  {acronym: 'SVC', name: 'Colon de El Salvador'},
  {acronym: 'SYP', name: 'Libra Síria'},
  {acronym: 'SZL', name: 'Lilangeni Suazilandês'},
  {acronym: 'THB', name: 'Baht Tailandês'},
  {acronym: 'TJS', name: 'Somoni do Tajiquistão'},
  {acronym: 'TMT', name: 'TMT'},
  {acronym: 'TND', name: 'Dinar Tunisiano'},
  {acronym: 'TRY', name: 'Nova Lira Turca'},
  {acronym: 'TTD', name: 'Dólar de Trinidad'},
  {acronym: 'TWD', name: 'Dólar Taiuanês'},
  {acronym: 'TZS', name: 'Shilling Tanzaniano'},
  {acronym: 'UAH', name: 'Hryvinia Ucraniana'},
  {acronym: 'UGX', name: 'Shilling Ugandês'},
  {acronym: 'USDT', name: 'Dólar Americano'},
  {acronym: 'UYU', name: 'Peso Uruguaio'},
  {acronym: 'UZS', name: 'Som Uzbequistanês'},
  {acronym: 'VEF', name: 'Bolívar Venezuelano'},
  {acronym: 'VND', name: 'Dong Vietnamita'},
  {acronym: 'VUV', name: 'Vatu de Vanuatu'},
  {acronym: 'XAF', name: 'Franco CFA Central'},
  {acronym: 'XAGG', name: 'Prata'},
  {acronym: 'XBR', name: 'Brent Spot'},
  {acronym: 'XCD', name: 'Dólar do Caribe Oriental'},
  {acronym: 'XOF', name: 'Franco CFA Ocidental'},
  {acronym: 'XPF', name: 'Franco CFP'},
  {acronym: 'XRP', name: 'XRP'},
  {acronym: 'YER', name: 'Riyal Iemenita'},
  {acronym: 'ZAR', name: 'Rand Sul-Africano'},
  {acronym: 'ZMK', name: 'Kwacha Zambiana'},
  {acronym: 'ZWL', name: 'Dólar Zimbabuense'},
  {acronym: 'XAU', name: 'Ouro'},
];

export const Coins = [
  {value: 'DKK', Label: 'Coroa Dinamarquesa'},
  {acronym: 'NOK', name: 'Coroa Norueguesa'},
  {acronym: 'SEK', name: 'Coroa Sueca'},
  {acronym: 'USD', name: 'Dólar Americano'},
  {acronym: 'AUD', name: 'Dólar Australiano'},
  {acronym: 'CAD', name: 'Dólar Canadense'},
  {acronym: 'NZD', name: 'Dólar Neozelandês'},
  {acronym: 'EUR', name: 'Euro'},
  {acronym: 'CHF', name: 'Franco Suíço'},
  {acronym: 'JPY', name: 'Iene Japonês'},
  {acronym: 'GBP', name: 'Libra Esterlina'},
  {acronym: 'ARS', name: 'Peso Argentino'},
  {acronym: 'CLP', name: 'Peso Chileno'},
  {acronym: 'COP', name: 'Peso Colombiano'},
  {acronym: 'MXN', name: 'Peso Mexicano'},
  {acronym: 'CNY', name: 'Yuan Chinês'},
];
